CREATE DATABASE QUANLYBANGDIA
USE QUANLYBANGDIA


CREATE TABLE THONGTINCANHAN
(
    CMND      VARCHAR(20)  NOT NULL ,
    HOTEN     NVARCHAR(70) NOT NULL,
    DIENTHOAI VARCHAR(20),
    DIACHI    NVARCHAR(150),
    GIOITINH  BIT NULL ,--0: NAM --1: NỮ
    NGAYSINH  DATE NOT NULL,

)

CREATE TABLE KHACHHANG
(
    MAKH       VARCHAR(10) NOT NULL,
    CMND       VARCHAR(20) NOT NULL,
    NGAYHETHAN DATE NOT NULL,

)

CREATE TABLE NHANVIEN
(
    MANV VARCHAR(10) NOT NULL,
    CMND VARCHAR(20) NOT NULL,
    MOTA NVARCHAR(100),

)

CREATE TABLE TAIKHOAN
(
    TENTAIKHOAN VARCHAR(30)   NOT NULL,
    MATKHAU     NVARCHAR(128) NOT NULL,
    LOAITK      BIT NULL,
    MANV        VARCHAR(10)   NOT NULL,

)


CREATE TABLE BANGDIA
(
    MABD        NVARCHAR(10) NOT NULL,
    TENBD       NVARCHAR(50) NOT NULL,
    HANGSANXUAT NVARCHAR(50) NOT NULL,
    GHICHU      NVARCHAR(100),
    DONGIA      MONEY        NOT NULL,
    TINHTRANG   BIT NULL, --1 CÒN, 0 HẾT
    THELOAI     NVARCHAR(30) NOT NULL,
    SOLUONGTON  INT          NOT NULL,

)


CREATE TABLE HOADON
(
    MAHD    VARCHAR(10) NOT NULL,
    NGAYLAP DATE NULL,
    MAKH    VARCHAR(10) NOT NULL,
    
)


CREATE TABLE CHITIETHOADON
(
    MAHD           VARCHAR(10)  NOT NULL,
    MABD           NVARCHAR(10) NOT NULL,
    SONGAYDUOCMUON INT          NOT NULL,
    SOLUONG        INT          NOT NULL,
    TINHTRANG      INT          NOT NULL,
   
)


alter table THONGTINCANHAN
add primary key(CMND)

alter table KHACHHANG
add primary key(MAKH)

alter table NHANVIEN
add primary key(MANV)

alter table TAIKHOAN
add primary key(TENTAIKHOAN)

alter table BANGDIA
add primary key(MABD)

alter table HOADON
add primary key(MAHD)

alter table CHITIETHOADON
add constraint MAHD_MABD primary key(MAHD,MABD)


ALTER TABLE KHACHHANG
ADD CONSTRAINT KHACHHANG_FK_THONGTINCANHAN FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND) ON DELETE CASCADE


ALTER TABLE NHANVIEN
ADD CONSTRAINT NHANVIEN_FK_THONGTINCANHAN FOREIGN KEY (CMND) REFERENCES THONGTINCANHAN (CMND) ON DELETE CASCADE

ALTER TABLE TAIKHOAN
ADD CONSTRAINT TAIKHOAN_FK_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV) ON DELETE CASCADE


	ALTER TABLE THONGTINCANHAN
ADD DEFAULT(0) FOR GIOITINH

	ALTER TABLE BANGDIA
ADD DEFAULT(0) FOR TINHTRANG

ALTER TABLE HOADON
ADD CONSTRAINT HOADON_FK_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG (MAKH)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT CHITIETHOADON_FK_BANGDIA FOREIGN KEY (MABD) REFERENCES BANGDIA (MABD)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT CHITIETHOADON_FK_HOADON FOREIGN KEY (MAHD) REFERENCES HOADON (MAHD) ON DELETE CASCADE

ALTER TABLE KHACHHANG
    ADD CONSTRAINT KHACHHANG_DF_NGAYHETHAN DEFAULT DATEADD(YEAR, 3, GETDATE()) FOR NGAYHETHAN
GO


ALTER TABLE HOADON
    ADD CONSTRAINT HOADON_DF_NGAYLAP DEFAULT GETDATE() FOR NGAYLAP
GO

CREATE VIEW VIEW_THONGTINKHACHHANG AS
SELECT T.CMND,
       K.MAKH,
       HOTEN,
       DIENTHOAI,
       DIACHI,
       GIOITINH,
       NGAYSINH,
       NGAYHETHAN
FROM THONGTINCANHAN T
         INNER JOIN KHACHHANG K
                    ON T.CMND = K.CMND
GO

CREATE VIEW VIEW_THONGTINNHANVIEN AS
SELECT T.CMND,
       N.MANV,
       HOTEN,
       DIENTHOAI,
       DIACHI,
       GIOITINH,
       NGAYSINH,
       MOTA
FROM THONGTINCANHAN T
         INNER JOIN NHANVIEN N
                    ON T.CMND = N.CMND
GO

CREATE VIEW VIEW_HOADON AS
SELECT H.MAHD, H.MAKH, H.NGAYLAP, C.MABD, C.SONGAYDUOCMUON, C.SOLUONG, C.TINHTRANG
FROM HOADON H
         INNER JOIN CHITIETHOADON C
                    ON H.MAHD = C.MAHD
GO

CREATE TRIGGER TRG_THEMHOADON
    ON CHITIETHOADON
    AFTER INSERT AS
BEGIN
    UPDATE BANGDIA
    SET SOLUONGTON = SOLUONGTON - (
        SELECT SOLUONG
        FROM inserted
        WHERE MABD = B.MABD
    )
    FROM BANGDIA B
             JOIN inserted I
                  ON B.MABD = I.MABD
END
GO

CREATE TRIGGER TRG_CAPNHATHOADON
    ON CHITIETHOADON
    AFTER UPDATE AS
BEGIN
    UPDATE BANGDIA
    SET SOLUONGTON = SOLUONGTON -
                     (SELECT SOLUONG FROM inserted WHERE MABD = B.MABD) +
                     (SELECT SOLUONG FROM deleted WHERE MABD = B.MABD)
    FROM BANGDIA B
             JOIN deleted D
                  ON B.MABD = D.MABD
end
GO

CREATE TRIGGER TRG_XOAHOADON
    ON CHITIETHOADON
    FOR DELETE AS
BEGIN
    UPDATE BANGDIA
    SET SOLUONGTON = SOLUONGTON + (
        SELECT SUM(SOLUONG)
        FROM deleted
        WHERE MABD = B.MABD)
    FROM BANGDIA B
             JOIN deleted D
                  ON B.MABD = D.MABD
END
GO

--========== FUNCTION ==========--
CREATE PROCEDURE RESET_DATABASE AS
BEGIN
    DELETE FROM CHITIETHOADON
    DELETE FROM HOADON
    DELETE FROM BANGDIA
    DELETE FROM TAIKHOAN WHERE TENTAIKHOAN != 'admin'
    DELETE
    FROM NHANVIEN
    WHERE MANV != (
        SELECT MANV
        FROM TAIKHOAN
        WHERE TENTAIKHOAN = 'admin'
    )
    DELETE FROM KHACHHANG
    DELETE
    FROM THONGTINCANHAN
    WHERE CMND != (
        SELECT CMND
        FROM TAIKHOAN T
                 JOIN NHANVIEN N ON T.MANV = N.MANV
        WHERE TENTAIKHOAN = 'admin'
    )
END
GO

CREATE PROCEDURE THANHTOAN_HOADON(@maHoaDon VARCHAR(10)) AS
BEGIN
    UPDATE CHITIETHOADON
    SET TINHTRANG = 1
    WHERE MAHD = @maHoaDon

    UPDATE BANGDIA
    SET SOLUONGTON = SOLUONGTON + (SELECT SOLUONG FROM CHITIETHOADON WHERE MAHD = @maHoaDon)
    WHERE MABD = (SELECT MABD FROM CHITIETHOADON WHERE MAHD = @maHoaDon)
END
GO
--========== THÊM DỮ LIỆU ==========--
INSERT INTO THONGTINCANHAN (CMND, HOTEN, DIENTHOAI, DIACHI, GIOITINH, NGAYSINH)
VALUES ('879632147', N'Nguyễn Thảo Uyên', '0982505701', N'12 GV', 0, '2002-03-24')
GO

INSERT INTO NHANVIEN (MANV, CMND, MOTA)
VALUES ('NV00001', '879632147', N'ADMIN')
GO

INSERT INTO TAIKHOAN (TENTAIKHOAN, MATKHAU, LOAITK, MANV)
VALUES ('admin', 'admin', 1, 'NV00001')
GO

INSERT INTO BANGDIA (MABD, TENBD, HANGSANXUAT, GHICHU, DONGIA, TINHTRANG, THELOAI, SOLUONGTON)
VALUES
('BD00001', N'CD Làn Sóng Xanh - 25 Năm Đi Cùng Nhạc Việt', N'Phương Nam', NULL, 20000.00, 1, N'Nhạc', 50),
('BD00002', N'Thu Tuyết - Thu Trắng 4 (CD Sách Nhạc)', N'Phương Nam', NULL, 20000.00, 1, N'Nhạc', 40),
('BD00003', N'DVD Mỹ Tâm Liveconcert - Heartbeat (VT)', N'Cty TNHH Dịch Vụ Giải Trí Mỹ Tâm', NULL, 30000.00, 1, N'Nhạc', 60),
('BD00004', N'Cậu Bé Cưỡi Rồng - Eragon (DVD)', N'Phương Nam Phim', NULL, 7000.00, 1, N'Phim nước ngoài', 30),
('BD00005', N'Bing & Bongs Big Adventures - Vol 4', N'Phương Nam phim', NULL, 10000.00, 1, N'Hoạt hình', 60),
('BD00006', N'Ludwig Van Beethoven Box', N'Phương Nam Phim', N'(Hộp Bộ - 9CD)', 300000.00, 1, N'Nhạc', 20),
('BD00007', N'Địa Chấn Ở Điện Biên Phủ', N'Hãng phim Tài liệu và Khoa Học Trung Ương', N'(DVD)', 10000.00, 1, N'Phim Tư Liệu', 30),
('BD00008', N'Châu Phi Hoang Dã', N'Phương Nam Phim', '(DVD)', 10000.00, 1, N'Chương trình động vật', 30),
('BD00009', N'Hà Anh Tuấn - LAVA', N'Phương Nam Phim', '(CD)', 20000.00, 1, N'Nhạc', 100),
('BD00010', N'Alvin And The Chipmunks 2 (DVD)', N'Phương Nam phim', N'Nhóm Sóc con với các giọng hát truyền cảm Alvin, Simon và Theodore trở lại sân khấu trong', 20000.00, 1, N'Phim thiếu nhi', 30),
('BD00011', N'Harry Potter Và Chiếc Cốc Lửa', N'Phương Nam phim', N'(Tập 4, DVD)', 20000.00, 1, N'Phim thiếu nhi', 50),
('BD00012', N'Kỷ Băng Hà 2 - Thời Băng Tan', N'Phương Nam phim', N'(DVD)', 15000.00, 1, N'Phim hoạt hình', 60),
('BD00013', N'Những Nụ Hôn Rực Rỡ', N'Phương Nam phim', N'(DVD)', 10000.00, 1, N'Phim Việt Nam', 20),
('BD00014', N'Đứa Con Và Người Lính', N'Phim Truyện Việt Nam', N'(DVD)', 10000.00, 1, N'Phim truyện Việt Nam', 60),
('BD00015', N'Sóng ở đáy sông', N'Hãng Phim Truyện Việt Nam', N'(Bộ 5 DVD)', 35000.00, 1, N'Phim Truyện Việt Nam', 60);

select * from BANGDIA
select*from VIEW_THONGTINKHACHHANG


-- Insert data into THONGTINCANHAN table
INSERT INTO THONGTINCANHAN (CMND, HOTEN, DIENTHOAI, DIACHI, GIOITINH, NGAYSINH)
VALUES
(234857963, N'Lê Thị Hồng Vương', '0337098001', 'TP Hồ Chí Minh', 0, '2007-10-30'),
(789421369, N'Đinh Hoàng Chiến', '0124786347', 'TP Hồ Chí Minh', 1, '2003-11-15'),
(985231469, N'Trần Hoàng Anh', '0596321478', 'TP Hồ Chí Minh', 0, '2003-11-21');

-- Insert data into KHACHHANG table
INSERT INTO KHACHHANG (CMND, MAKH, NGAYHETHAN)
VALUES
(234857963, 'KH00001', '2026-11-10'),
(789421369, 'KH00002', '2026-11-10'),
(985231469, 'KH00003', '2026-11-11');
